server:
  port: 9595

spring:
  application:
    name: notification-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1604}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-keycloak-auth:8080/realms/ITM-Advice

